---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: osl-config
  data:
    application.properties: |-
      spring.profiles.active=jdbc
      spring.application.name=config
      spring.cloud.config.label=latest
      spring.datasource.hikari.connection-timeout=5000
      spring.datasource.hikari.maximum-pool-size=10
      spring.datasource.driver-class-name=org.postgresql.Driver
      spring.cloud.config.server.jdbc.sql=select prop_key, value from mobile_app_owner.properties where application=? and profile=? and label=?
      spring.cloud.config.server.jdbc.order=1
      spring.datasource.url=${JDBC_URL}
      spring.datasource.username=${DB_USERNAME}
      spring.datasource.password=${DB_PASSWORD}
- apiVersion: v1
  kind: Secret
  metadata:
    name: psql-osl-stg
  type: Opaque
  data:
    jdbcUrl: amRiYzpwb3N0Z3Jlc3FsOi8vcHNxbC1vc2wxLXFhdC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9hZ3Jjb21tb24/c3NsbW9kZT1yZXF1aXJl
    password: U2tNYlVMeSFUSnFRNU5WOSVQUVJEbjZPVEZwWkswayM=
    username: YWdyY29tbW9u
###$ cd /C/Users/U624415/AppData/Roaming/JetBrains/IntelliJIdea2025.3/scratches/k8s-local/secret-db.yaml
