apiVersion: v1
kind: Secret
metadata:
  name: elastic-apm
type: Opaque
data:
  secret-token: bWxZR1A1WWlJQUxZRnJLeEVo
  server-urls: aHR0cHM6Ly82NWIzZjQyZjQ4Mzc0ZTM5OTFiNDc2ZjU5MDliOWY4OC5hcG0ucHJpdmF0ZWxpbmsuZWFzdHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tOjQ0Mw==
### to encode. run on linux: echo -n "https://65b3f42f48374e3991b476f5909b9f88.apm.privatelink.eastus.azure.elastic-cloud.com" | base64


#  rsql-txn-app-modernization-dev
#  jdbcUrl: r2dbc:sqlserver://WACORPCLUT1.amer.iberdrola.local:1433
#  username: ivr_wfm_owner
#  password: 1_istlLon1iest#
  
  
  
